### ISSUE TITLE
I cannot kill Herobrine Phase 3

### ISSUE THREAD

**Issue by Gamer98YT** [TheMinecraftOverlordYT/herobrinemod#5]
Hello, i was trying this mod and when i spawn Herobrine phase 3 and i cant kill it, the health bar does not drop.

Pd: I love this mod!!!

**Comment by Gamer98YT** [comment]
Ok, yes i can but idk if the collision its made like that or the collision is not programmed yet.

**Comment by ketan-ryan** [comment]
Phase 3 is not yet implemented
